// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-bookings.ts
import { createClient } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_bookings_default = defineTool({
  name: "list_bookings",
  title: "List bookings",
  description: "List bookings visible to the signed-in user. Supports optional date-range filtering and result limit. Returns job code, dates, status, artist/client/venue ids, and fees.",
  inputSchema: {
    from: z.string().optional().describe("Optional start date filter (YYYY-MM-DD or ISO). Only bookings with start_date >= from are returned."),
    to: z.string().optional().describe("Optional end date filter (YYYY-MM-DD or ISO). Only bookings with start_date <= to are returned."),
    status: z.string().optional().describe("Optional status filter (e.g. confirmed, pending, cancelled)."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("bookings").select("id, job_code, start_date, finish_date, status, artist_id, client_id, venue_id, sell_fee, buy_fee, artist_status, client_status").order("start_date", { ascending: false }).limit(limit ?? 50);
    if (from) q = q.gte("start_date", from);
    if (to) q = q.lte("start_date", to);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { bookings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-booking.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_booking_default = defineTool2({
  name: "get_booking",
  title: "Get booking",
  description: "Fetch a single booking by id, including all columns, for the signed-in user.",
  inputSchema: {
    id: z2.string().uuid().describe("Booking id (uuid).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("bookings").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Booking not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { booking: data }
    };
  }
});

// src/lib/mcp/tools/list-artists.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_artists_default = defineTool3({
  name: "list_artists",
  title: "List artists",
  description: "List artists visible to the signed-in user, optionally filtered by name substring.",
  inputSchema: {
    search: z3.string().optional().describe("Optional case-insensitive name substring."),
    limit: z3.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser3(ctx).from("artists").select("id, name, act_code, act_type, email, phone, vat_rate").order("name").limit(limit ?? 100);
    if (search) q = q.ilike("name", `%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { artists: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-clients.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_clients_default = defineTool4({
  name: "list_clients",
  title: "List clients",
  description: "List clients visible to the signed-in user, optionally filtered by name substring.",
  inputSchema: {
    search: z4.string().optional(),
    limit: z4.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser4(ctx).from("clients").select("id, name, email, phone, is_venue_operator").order("name").limit(limit ?? 100);
    if (search) q = q.ilike("name", `%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { clients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-venues.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^3.25.76";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_venues_default = defineTool5({
  name: "list_venues",
  title: "List venues",
  description: "List venues visible to the signed-in user, optionally filtered by name substring.",
  inputSchema: {
    search: z5.string().optional(),
    limit: z5.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser5(ctx).from("venues").select("id, name, location_id, capacity").order("name").limit(limit ?? 100);
    if (search) q = q.ilike("name", `%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { venues: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-invoices.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z6 } from "npm:zod@^3.25.76";
function supabaseForUser6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_invoices_default = defineTool6({
  name: "list_invoices",
  title: "List invoices",
  description: "List invoices visible to the signed-in user, with optional status filter.",
  inputSchema: {
    status: z6.string().optional().describe("Optional status filter: draft, sent, cancelled, paid."),
    limit: z6.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser6(ctx).from("invoices").select("*").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { invoices: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "whazayczomsdlluhcnke";
var mcp_default = defineMcp({
  name: "showpro-mcp",
  title: "ShowPro Booking System",
  version: "0.1.0",
  instructions: "Tools for the ShowPro entertainment booking system. Use these to look up bookings, artists, clients, venues, and invoices for the signed-in user. All tools respect the user's row-level security and return only data the user is permitted to see.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_bookings_default, get_booking_default, list_artists_default, list_clients_default, list_venues_default, list_invoices_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
